# Generated by Django 5.0 on 2024-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
