# Generated by Django 5.0 on 2024-01-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
                ('maincategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
    ]
