# Generated by Django 5.0 on 2024-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0005_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='offertype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
