# Generated by Django 5.0 on 2024-02-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0006_alter_productdetail_offertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='productsubnamedescription',
            new_name='productsubdescription',
        ),
    ]
