# Generated by Django 5.0.6 on 2024-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
