# Generated by Django 5.0.6 on 2024-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0009_alter_productdetail_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pictures',
            field=models.TextField(default=''),
        ),
    ]
