# Generated by Django 5.0.6 on 2024-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0011_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='maincategories',
            field=models.ManyToManyField(to='sevenshadesapp.maincategory'),
        ),
    ]
