# Generated by Django 5.0.6 on 2024-06-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0012_brand_maincategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brandid',
        ),
        migrations.AddField(
            model_name='product',
            name='brandids',
            field=models.ManyToManyField(to='sevenshadesapp.brand'),
        ),
    ]
