# Generated by Django 5.0.6 on 2024-07-24 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0013_remove_product_brandid_product_brandids'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
